/**:
  ros__parameters:
    use_sim_time: false
    frames/odom: odom
    frames/baselink: gimbal
    frames/lidar: fusion_lidar
    frames/imu: fusion_imu
    publish/pose_odom: true
    publish/keyframes: true
    pointcloud/deskew: false
    pointcloud/voxelize: true
    imu/calibration: false
    odom/computeTimeOffset: false
    odom/keyframe/threshD: 1.0
    odom/keyframe/threshR: 15.0
    odom/preprocessing/voxelFilter/res: 0.25
    odom/preprocessing/cropBoxFilter/size: 1.0
    odom/submap/keyframe/knn: 10
    odom/submap/keyframe/kcv: 10
    odom/submap/keyframe/kcc: 10
    odom/gicp/minNumPoints: 64
    odom/gicp/kCorrespondences: 16
    odom/gicp/maxCorrespondenceDistance: 0.5
    odom/gicp/maxIterations: 32
    odom/gicp/transformationEpsilon: 0.01
    odom/gicp/rotationEpsilon: 0.01
    odom/gicp/initLambdaFactor: 1.0e-9
